// modernized/frontend/src/screens/AccountView.tsx
// Account View screen (legacy COACTVWC / tran CAVW).
// REQ-F-010..REQ-F-015: account search validation and combined
// account + customer display.

import { useState, type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api, ApiError, type AccountDetail } from '../api/client';
import { Screen, type ScreenMessage } from '../components/Screen';
import { validateAccountId } from '../validation';

export function AccountView() {
  const [searchParams] = useSearchParams();
  const [accountId, setAccountId] = useState(searchParams.get('accountId') ?? '');
  const [detail, setDetail] = useState<AccountDetail | null>(null);
  const [message, setMessage] = useState<ScreenMessage | null>(null);

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    const err = validateAccountId(accountId);
    if (err) {
      setMessage({ text: err, kind: 'error' });
      setDetail(null);
      return;
    }
    try {
      const res = await api.getAccount(accountId.trim());
      setDetail(res);
      setMessage(null);
    } catch (apiErr) {
      setDetail(null);
      setMessage({
        text: apiErr instanceof ApiError ? apiErr.message : 'Unable to lookup Account...',
        kind: 'error',
      });
    }
  }

  return (
    <Screen tranId="CAVW" program="COACTVWC" title="View Account" message={message} backTo="/menu">
      <form onSubmit={onSubmit} className="actions" aria-label="Account search">
        <div className="field">
          <label htmlFor="accountId">Account Number</label>
          <input
            id="accountId"
            value={accountId}
            maxLength={11}
            onChange={(e) => setAccountId(e.target.value)}
          />
        </div>
        <button type="submit" className="btn">
          Search
        </button>
      </form>
      {detail && (
        <div className="form-grid" style={{ marginTop: 16 }}>
          <fieldset>
            <legend>Account</legend>
            <dl className="detail">
              <dt>Account ID</dt>
              <dd>{detail.account.id}</dd>
              <dt>Active</dt>
              <dd>{detail.account.activeStatus ? 'Y' : 'N'}</dd>
              <dt>Current Balance</dt>
              <dd>{detail.account.currentBalance}</dd>
              <dt>Credit Limit</dt>
              <dd>{detail.account.creditLimit}</dd>
              <dt>Cash Credit Limit</dt>
              <dd>{detail.account.cashCreditLimit}</dd>
              <dt>Open Date</dt>
              <dd>{detail.account.openDate}</dd>
              <dt>Expiry Date</dt>
              <dd>{detail.account.expirationDate}</dd>
              <dt>Reissue Date</dt>
              <dd>{detail.account.reissueDate ?? '-'}</dd>
              <dt>Cycle Credit</dt>
              <dd>{detail.account.currCycleCredit}</dd>
              <dt>Cycle Debit</dt>
              <dd>{detail.account.currCycleDebit}</dd>
              <dt>Group ID</dt>
              <dd>{detail.account.groupId ?? '-'}</dd>
            </dl>
          </fieldset>
          <fieldset>
            <legend>Customer</legend>
            <dl className="detail">
              <dt>Customer ID</dt>
              <dd>{detail.customer.id}</dd>
              <dt>Name</dt>
              <dd>
                {detail.customer.firstName} {detail.customer.middleName ?? ''} {detail.customer.lastName}
              </dd>
              <dt>Address</dt>
              <dd>
                {detail.customer.addressLine1} {detail.customer.addressLine2 ?? ''}
              </dd>
              <dt>State / Zip</dt>
              <dd>
                {detail.customer.stateCode} {detail.customer.zipCode}
              </dd>
              <dt>Country</dt>
              <dd>{detail.customer.countryCode}</dd>
              <dt>Phone 1</dt>
              <dd>{detail.customer.phoneNumber1 ?? '-'}</dd>
              <dt>SSN</dt>
              <dd>***-**-{detail.customer.ssn.slice(-4)}</dd>
              <dt>Date of Birth</dt>
              <dd>{detail.customer.dateOfBirth}</dd>
              <dt>FICO Score</dt>
              <dd>{detail.customer.ficoCreditScore}</dd>
              <dt>Primary Holder</dt>
              <dd>{detail.customer.primaryCardHolder ? 'Y' : 'N'}</dd>
            </dl>
          </fieldset>
        </div>
      )}
    </Screen>
  );
}

// frontend/src/app/account-view/account-view.component.ts
import { Component, HostListener, inject } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { classifyAidKey } from '../shared/invalid-key';
import {
  AccountFieldState,
  AccountViewAccount,
  AccountViewCustomer,
  AccountViewResponse,
  AccountViewService
} from './account-view.service';

export const ACCOUNT_VIEW_PROMPT = 'Enter or update id of account to display';
export const ACCOUNT_VIEW_TRANSACTION = 'CAVW';
export const ACCOUNT_VIEW_PROGRAM = 'COACTVWC';
export const ACCOUNT_VIEW_EXIT_ROUTE = '/menu';

/**
 * View Account screen, equivalent of BMS map CACTVWA (app/bms/COACTVW.bms) driven by
 * COACTVWC: 11-char account field, account and customer detail blocks, 45-char info line,
 * 78-char error line (FR-S02-01..07, 13, 14). ENTER submits; F3 / Exit returns to the
 * main menu (FR-S02-11); every other function key is treated as ENTER (FR-S02-12).
 */
@Component({
  selector: 'app-account-view',
  standalone: true,
  imports: [FormsModule, MatButtonModule, MatCardModule, MatFormFieldModule, MatInputModule],
  templateUrl: './account-view.component.html',
  styleUrl: './account-view.component.scss'
})
export class AccountViewComponent {
  private readonly accountViewService = inject(AccountViewService);
  private readonly router = inject(Router);

  readonly transaction = ACCOUNT_VIEW_TRANSACTION;
  readonly program = ACCOUNT_VIEW_PROGRAM;
  readonly title = 'View Account';

  accountId = '';
  accountFieldState: AccountFieldState = 'blank';
  infoMessage = ACCOUNT_VIEW_PROMPT;
  errorMessage = '';
  account: AccountViewAccount | null = null;
  customer: AccountViewCustomer | null = null;
  reentered = false;

  /** 1300-SETUP-SCREEN-ATTRS: DFHRED when the filter is not ok, or blank on re-entry. */
  get accountFieldRed(): boolean {
    return this.accountFieldState === 'invalid' || (this.accountFieldState === 'blank' && this.reentered);
  }

  submit(): void {
    this.accountViewService.view(this.accountId).subscribe({
      next: (response) => this.apply(response),
      error: (error: HttpErrorResponse) => {
        const body = error.error as Partial<AccountViewResponse> | null;
        if (body && typeof body.errorMessage === 'string' && body.outcome === 'storeError') {
          this.apply(body as AccountViewResponse);
        }
      }
    });
  }

  exit(): void {
    this.router.navigateByUrl(ACCOUNT_VIEW_EXIT_ROUTE);
  }

  @HostListener('window:keydown', ['$event'])
  onKeydown(event: KeyboardEvent): void {
    const action = classifyAidKey(event);
    if (!action) {
      return;
    }
    event.preventDefault();
    if (action === 'exit') {
      this.exit();
    } else {
      this.submit();
    }
  }

  private apply(response: AccountViewResponse): void {
    this.reentered = true;
    this.accountId = response.accountId;
    this.accountFieldState = response.accountFieldState;
    this.infoMessage = response.infoMessage;
    this.errorMessage = response.errorMessage;
    this.account = response.account;
    this.customer = response.customer;
  }
}

<mat-card class="account-view-card">
  <div class="screen-header">
    <span data-testid="tran-name">Tran: {{ transaction }}</span>
    <span class="screen-title">AWS Mainframe Modernization</span>
    <span data-testid="prog-name">Prog: {{ program }}</span>
    <span class="screen-title">CardDemo</span>
  </div>
  <mat-card-header>
    <mat-card-title>{{ title }}</mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <form (ngSubmit)="submit()">
      <div class="row">
        <mat-form-field appearance="outline" class="account-field" [class.field-error]="accountFieldRed">
          <mat-label>Account Number :</mat-label>
          <input
            matInput
            name="accountId"
            [(ngModel)]="accountId"
            maxlength="11"
            autocomplete="off"
            data-testid="account-id-input"
          />
        </mat-form-field>
        <span class="field"><label>Active Y/N: </label><output data-testid="active-status">{{ account?.activeStatus }}</output></span>
      </div>

      <section class="detail-block" data-testid="account-block">
        <div class="row">
          <span class="field"><label>Opened:</label><output data-testid="open-date">{{ account?.openDate }}</output></span>
          <span class="field"><label>Credit Limit :</label><output data-testid="credit-limit">{{ account?.creditLimit }}</output></span>
        </div>
        <div class="row">
          <span class="field"><label>Expiry:</label><output data-testid="expiration-date">{{ account?.expirationDate }}</output></span>
          <span class="field"><label>Cash credit Limit :</label><output data-testid="cash-credit-limit">{{ account?.cashCreditLimit }}</output></span>
        </div>
        <div class="row">
          <span class="field"><label>Reissue:</label><output data-testid="reissue-date">{{ account?.reissueDate }}</output></span>
          <span class="field"><label>Current Balance :</label><output data-testid="current-balance">{{ account?.currentBalance }}</output></span>
        </div>
        <div class="row">
          <span class="field"></span>
          <span class="field"><label>Current Cycle Credit:</label><output data-testid="cycle-credit">{{ account?.currentCycleCredit }}</output></span>
        </div>
        <div class="row">
          <span class="field"><label>Account Group:</label><output data-testid="group-id">{{ account?.groupId }}</output></span>
          <span class="field"><label>Current Cycle Debit :</label><output data-testid="cycle-debit">{{ account?.currentCycleDebit }}</output></span>
        </div>
      </section>

      <h3 class="block-title">Customer Details</h3>
      <section class="detail-block" data-testid="customer-block">
        <div class="row">
          <span class="field"><label>Customer id :</label><output data-testid="customer-id">{{ customer?.customerId }}</output></span>
          <span class="field"><label>SSN:</label><output data-testid="ssn">{{ customer?.ssn }}</output></span>
        </div>
        <div class="row">
          <span class="field"><label>Date of birth:</label><output data-testid="date-of-birth">{{ customer?.dateOfBirth }}</output></span>
          <span class="field"><label>FICO Score:</label><output data-testid="fico-score">{{ customer?.ficoScore }}</output></span>
        </div>
        <div class="row three">
          <span class="field"><label>First Name</label><output data-testid="first-name">{{ customer?.firstName }}</output></span>
          <span class="field"><label>Middle Name: </label><output data-testid="middle-name">{{ customer?.middleName }}</output></span>
          <span class="field"><label>Last Name : </label><output data-testid="last-name">{{ customer?.lastName }}</output></span>
        </div>
        <div class="row">
          <span class="field wide"><label>Address:</label><output data-testid="address-line1">{{ customer?.addressLine1 }}</output></span>
          <span class="field narrow"><label>State </label><output data-testid="state">{{ customer?.state }}</output></span>
        </div>
        <div class="row">
          <span class="field wide"><label></label><output data-testid="address-line2">{{ customer?.addressLine2 }}</output></span>
          <span class="field narrow"><label>Zip</label><output data-testid="zip">{{ customer?.zip }}</output></span>
        </div>
        <div class="row">
          <span class="field wide"><label>City </label><output data-testid="city">{{ customer?.city }}</output></span>
          <span class="field narrow"><label>Country</label><output data-testid="country">{{ customer?.country }}</output></span>
        </div>
        <div class="row">
          <span class="field"><label>Phone 1:</label><output data-testid="phone1">{{ customer?.phone1 }}</output></span>
          <span class="field"><label>Government Issued Id Ref : </label><output data-testid="government-id">{{ customer?.governmentIssuedId }}</output></span>
        </div>
        <div class="row three">
          <span class="field"><label>Phone 2:</label><output data-testid="phone2">{{ customer?.phone2 }}</output></span>
          <span class="field"><label>EFT Account Id: </label><output data-testid="eft-account-id">{{ customer?.eftAccountId }}</output></span>
          <span class="field"><label>Primary Card Holder Y/N:</label><output data-testid="primary-card-holder">{{ customer?.primaryCardHolder }}</output></span>
        </div>
      </section>

      <div class="info-message" data-testid="info-message">{{ infoMessage }}</div>
      <div class="error-message" role="alert" data-testid="error-message">{{ errorMessage }}</div>

      <div class="actions">
        <button mat-flat-button color="primary" type="submit" data-testid="enter-button">Enter</button>
        <button mat-stroked-button type="button" (click)="exit()" data-testid="exit-button">Exit (F3)</button>
      </div>
    </form>
  </mat-card-content>
</mat-card>
